source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'

xcodeproj 'LGFilterViewDemo'

target 'LGFilterViewDemo' do
    pod 'LGFilterView', :path => '../'
    pod 'LGDrawer', '~> 1.0.0'
    pod 'LGViews', '~> 1.0.0'
    pod 'LGHelper', '~> 1.0.0'
end
